### ISSUE TITLE
Tooltip is getting truncated for tooltip-left component

### ISSUE THREAD

**Issue by hkrishna29** [cengage/react-magma#1000]
**Steps to reproduce the behavior:**

1. Go to 'https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/tooltip--left'
2. The view should be portrait mode
3. Enter position as 'left' in Control
4. Click on 'Tooltip Trigger' button
3. Note the tooltip is getting truncated 

**Expected behavior**
Tool tip should not get truncated

**Screenshots**
https://somup.com/c0VThtxZxG

**OS / Br**
ipad/Safari 15 / 9th generation 

**Note**:
The 'position' control option should be a dropdown with options, left , right above and below

**Comment by orion-cengage** [comment]
Everything is working as expected. If there was enough room on the right side to show the tooltip, then "popper.js" would automatically move it over there. But because there isn't enough room on either side, it just forces it to show on the left. This is actually an example of when a designer and developer should adjust the width of the tooltip to make sure it doesn't get cut off.
