### ISSUE TITLE
Style update: Focus style on inputs

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#1294]
**Purpose:** Update focus style on inputs to simplify and polish up presentation.

Components impacted:

- Text field
- Text area
- Number
- Date
- Time
- Search
- Password
- Select
- Native select
- Combobox

To achieve this update, all we need to do is update the pixel offset of the outline to -1px.

![image](https://github.com/cengage/react-magma/assets/24397282/8eb04ab6-a3b0-49a0-bba0-1871e0dee02e)

Screenshot of current focus style:

![image](https://github.com/cengage/react-magma/assets/24397282/624c20a1-cd13-4b0c-9d81-5771c89aebc2)

Screenshot of desired style:

![image](https://github.com/cengage/react-magma/assets/24397282/f753a535-2306-44bd-828d-ec836cd6c48d)

![image](https://github.com/cengage/react-magma/assets/24397282/081515d8-d36b-4a4d-9bb5-69507bf14f6a)

**Comment by chris-cedrone-cengage** [comment]
Confirm that Inputs have -1px border outline when focused instead of 2px

Text field ✅
Text area ✅
Number ✅
Date ✅
Time ✅
Search ✅
Password ✅
Select ✅
Native select ✅
Combobox ✅

**All verified with Chrome Version 130.0.6723.70, Safari 18 and Firefox 132.0 using Mac OS Sonoma 14.7 on:**
https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/datepicker--default

**Comment by orion-cengage** [comment]
I tested the following:

Text field ✅
Text area ✅
Number ✅
Date ✅
Time ✅
Search ✅
Password ✅
Select ✅
Native select ✅
Combobox ✅

MacOS 14.7.1
Chrome 128.0.6613.138
Firefox 132.0.1
Safari 18.1

https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/accordion--default
