### ISSUE TITLE
Vertical scrolling tabs - Scroll buttons prevent some items from being viewed and interacted with

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#193]
**Describe the bug**
Using the scroll buttons, it’s scrolling certain items out of view so you can’t interact with them, rather than being a little more aware of the content it’s scrolling through.  Scrolling with a mouse-wheel or finger doesn’t have this problem, but not everyone will be able to interact with it in this way.   Like in my screenshots below, you don’t see the 5th item using the scroll buttons.

**To Reproduce**
1. Set up a list of vertical tabs with probably at least 15 items, and restrict the height of the container to 200-300px
2. Click the Scroll Down button to see the next group, and you'll probably see that the previous bottom item that was blocked by the Scroll Down button is now scrolled up out of view or blocked by the Scroll Up button.

**Expected behavior**
I think we need to make sure this thing is somehow more aware of what is visible.  Somehow compensating for the Scroll Up/Down buttons.

**Screenshots**
In the screenshots below, you'll see you never get to see or interact with the 5th item, and most of the 6th item, if you use the Scroll Buttons.

![image](https://user-images.githubusercontent.com/24397282/110951327-905f2c00-830a-11eb-9d30-38468107260d.png)

![image](https://user-images.githubusercontent.com/24397282/110951362-99e89400-830a-11eb-9220-0625632feea1.png)

**Comment by joasmi723** [comment]
A similar/related issue was reported in the #react-magma channel:

We are (ANZ Nelson Hub team) faced with the problem that blurred scroll button is not accessible by tabbing and isn't visible by screen reader.
Actual result:
Blurred scroll button is not accessible by tabbing and can't be read by screen reader. Please, see the attachment below 
Expected result:
Blurred scroll button is accessible by tabbing and can be read by screen reader



![button_issue](https://user-images.githubusercontent.com/18616182/112004048-70d8b800-8aef-11eb-866d-d797bf310d20.png)

**Comment by joasmi723** [comment]
Sandbox to repro here:  https://codesandbox.io/s/react-magma-example-forked-nerrj?file=/example.tsx

It looks like right now, users can get to all of the tabs if they use the arrow keys to navigate through them.  This is how it is expected most screen reader users and (keyboard only users in general) users would navigate through them.  The unordered list has an aria label on it that reads Sample Vertical Tabs, use the down and up arrow keys to activate other tabs, so screen reader users would get that instruction.

The intent was that screen reader users would not be expected to use the scroll buttons at all, just the arrow keys.  Because of that, it would probably be best if those buttons were removed from the tab order and had aria-hidden attributes on them, so they wouldn't throw that a11y error.

While not a showstopper, the scroll behavior shold be better fine-tuned for those who are using both a combination of mouse and keyboard.
