### ISSUE TITLE
Data Viz - Line Chart

### ISSUE THREAD

**Issue by joasmi723** [cengage/react-magma#199]
Placeholder ticket for creating data visualization components.  

We should look into whether we can wrap features of the Victory library:
 https://formidable.com/open-source/victory/

Mockups:  
https://cengage.invisionapp.com/d/main#/projects/prototypes/20428082

**Comment by rcgillet** [comment]
*Purpose**:* Implement initial design for line chart using D3.  This is primarily for proof of concept, so nothing is totally final.

*inVision:* [https://cengage.invisionapp.com/share/DFYID3TKE9W]

*Inspiration:*
 * [https://www.carbondesignsystem.com/data-visualization/basic-charts#line]
 * [https://www.fusioncharts.com/charts/line-area-charts/line-chart-with-multiple-series?framework=react]

h3. Acceptance Criteria
 # Component width = 100% of the container it's inside of 
 # Title (required)
 # Description (optional)
 # Tabs - Two tabs allowing quick navigation between chart and data table
 # Tools
 ## Export
 ## Full-screen
 # Color Palette
 ## The color palette is custom, based on the current brand colors.  This color palette is meant only for Data Viz
 ## The following colors should be used for lines/bars/etc. in this order
 ### #0085CC
 ### #E0004D
 ### #FA6600
 ### #48A200
 ### #B12FAD
 ### #00A393
 ### #00507A
 ### #8F0033
 ### #B84900
 ### #255200
 ### #711E6E
 ### #005249
 # Line Chart
 ## X and Y-axis titles (required)
 ### Y-axis is rotated to be vertical which is standard behavior
 #### We are adding an icon to the end of our Y-axis title to indicate the following behavior:
 #### Hovering over the Y-axis title shows easier to read horizontal title in card-based popover
 ### Y-axis values are dynamically generated in order to best use the space allowed.  You can see this in action in the Inspiration examples above.
 ## The lines are 3px thick and made up of multiple nodes connected by solid lines.
 ### Hovering or placing focus on the node fills in the circle and reveals the value in a card-based popover
 ## Hovering on or within 16px of the line that multiple nodes share, reveals the values for every node in a card-based popover.  (See example in inVision)
 ## The lines should animate into view when the chart loads.  For lines this looks like they're being drawn from left to right.
 # Legend
 ## The legend serves as not only the way to understand what each line represents, but also allows you to hide/show any of the data sets available.
 ## By default, all data sets are turned on, represented by modified checkbox filled with associated color.  The actual checkmark icon is not displayed, in order to maximize the visibility of the color, and possible future pattern.
 ## Clicking on one of the data sets hides it from the chart above.
 ### Hiding a data set could cause the Y-axis scale to change and optimize the view
 # Keyboard Navigation
 ## Examples: [https://www.fusioncharts.com/extensions/accessibility] 
 ## Press TAB to focus on the chart.
 ## Press TAB again to focus on the first data plot.
 ## Press TAB again to focus on the first data plot.
 *** Use LEFT and RIGHT ARROW keys to navigate through data plots of the same series.
 *** Use TOP and DOWN ARROW keys to navigate to adjacent series.
 ## Press TAB again to focus on the first legend item.
 *** Use ARROW keys to navigate through legend items.
 *** Use ENTER/SPACEBAR key to hide/unhide the series.
 # Data table
 ## Display raw data for the chart using RM data table component
 # Responsive behavior
 ## The chart should resize based on the size of the container.  Not sure if this should be done only on page load or browser resize.  My understanding is that doing it on browser resize could have poor performance.
