### ISSUE TITLE
react-magma-docs: (1) New page - Versions

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#316]
This new page is part of the update to RM 3.

**inVision link:** https://cengage.invisionapp.com/share/YZ11CUAOSUPC

### AC's

- Create new page titled "React Magma Versions"
- Put "React Magma Versions" in the "Developing" section
![image](https://user-images.githubusercontent.com/24397282/125647641-579e4b1c-109d-4be6-8226-5ac8f7b5a076.png)

- Clicking on the version tag in the header will also bring you to the "Versions" page.
![image](https://user-images.githubusercontent.com/24397282/125336175-128c4b00-e313-11eb-934d-533fd9bc019e.png)

- Page content and copy can be found in inVision.  Use Inspect mode for easier copy and paste
- The versions are displayed in tables.  Each row contains the following:
-- Version # 
-- Release date
-- Link to docs site
![image](https://user-images.githubusercontent.com/24397282/125349721-82a2cd00-e323-11eb-8725-e5af2efa9cf1.png)

**Comment by Uditsingh67** [comment]
AC's

1. Create new page titled "React Magma Versions" : **PASS**
2. Put "React Magma Versions" in the "Developing" section : **PASS**
3. Clicking on the version tag in the header will also bring you to the "Versions" page. : **FAIL Due to #936**
4. Page content and copy can be found in inVision. Use Inspect mode for easier copy and paste : ** This AC is Not Clear need Clarification **
5. The versions are displayed in tables. Each row contains the following: : **PASS**
-- Version #
-- Release date
-- Link to docs site

**Comment by silvalaura** [comment]
@Uditsingh67 There was a change in requirements and the version tag is no longer expected to be visible on the header. If everything else passes, let's close this.

**Comment by Uditsingh67** [comment]
**AC's**
Create new page titled "React Magma Versions" **: PASS**
Put "React Magma Versions" in the "Developing" section **: PASS**

Page content and copy can be found in inVision. Use Inspect mode for easier copy and paste : 
The versions are displayed in tables. Each row contains the following: : **PASS**
-- Version #
-- Release date
-- Link to docs site
**See Screen-cast :** http://somup.com/c36FnAvbeU
Thanks!
