### ISSUE TITLE
The displayed option in 'Rows per page' is not highlighted in the drop down list

### ISSUE THREAD

**Issue by hkrishna29** [cengage/react-magma#393]
**Describe the bug**
The displayed option in 'Rows per page' is not highlighted in the drop down list

**To Reproduce**
1. Go to 'https://storybook-preview-319--upbeat-sinoussi-f675aa.netlify.app/?path=/story/fileuploader--csv'
2. Click on 'Browse Files'
3. Upload file
4. Click on 'Rows per page' drop down
5. Select any option ( eg:100)
6. Verify the selected option is displayed 
7. Click on the drop down 
8. Notice that the displayed option (100) is not selected but option '10' is

**Expected behavior**
The displayed option in 'Rows per page' is not highlighted in the drop down list

**Screenshots**
https://screencast-o-matic.com/watch/cr6XrIVXOWd

**Desktop (please complete the following information):**
OS: [Win 10]
Browser [chrome,]
Version [Version 94.0.4606.81 (64-bit)]

**Additional context**
[gradebookExport (4).csv](https://github.com/cengage/react-magma/files/7340559/gradebookExport.4.csv)

**Comment by orion-cengage** [comment]
I definitely hear what you're saying, and the design docs might need to be updated as a result.  So let's figure this out.

I might argue that we're actually showing the selected value just fine because we're updating the label of the button itself?
![image](https://user-images.githubusercontent.com/24397282/137203303-164d52ad-58e1-4a26-919f-31ce7c24e858.png)

But is that good enough?  What is semantically the best option here?  Does it matter?

Carbon is using a Select: https://www.carbondesignsystem.com/components/pagination/usage

**Comment by orion-cengage** [comment]
I can't say I understand everything you're saying, but if you're OK with using the dropdown in this component, then go for it.  Let's turn on the "selected" state in this instance as you recommended.

**Comment by greenervigil** [comment]
Please test on most recent version of storybook:  

https://storybook-preview-632--upbeat-sinoussi-f675aa.netlify.app/?path=/story/dropzone--csv

Note on the Dropdown button:  According to the documentation with the use of activeItem prop: 

The activeIndex prop can be used to set an item within the dropdown as active. When another item is selected, that item will become active and the menu will remain open, rather than closing as usual.

**Comment by Uditsingh67** [comment]
We Verified the issue and Notice that the displayed option (100) is selected but option '10' is still highlighted in the drop down list. It is desired?
See Screen-cast : https://www.screenpresso.com/=uV1rf
Hence, Reopening the ticket.
Thanks!

**Comment by silvalaura** [comment]
**Notes for testing:**

- Verify that [Tables with pagination](https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/table--controlled-pagination) use a native select (instead of the dropdown component) 
- Confirm the focus issue noted above is resolved

**Comment by hkrishna29** [comment]
the issue no longer exists http://somup.com/c0n1Y2x5hZ 
https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/table--controlled-pagination
