### ISSUE TITLE
Bug_Datagrid> All components> isInverse control prop> Preview gets blank if 'isInverse' control prop is 'True'.

### ISSUE THREAD

**Issue by priya-rajput** [cengage/react-magma#539]
**Describe the bug**
Preview gets blank if 'isInverse' control prop is 'True' for the following.
Default
Colored Rows : Background gets disappear if 'isInverse' control prop is 'True'.
Selectable
Controlled Selectable
Disabled Selectable Row
Pagination Changed Defaults
Controlled Pagination
Without Pagination
Pagination With Custom Component

**To Reproduce**
1. Go to 'https://storybook-preview-290--upbeat-sinoussi-f675aa.netlify.app/?path=/story/datagrid--default'
2. Click on 'Controls'
3. Select the 'isInverse' control prop
4. Toggle it into 'True'
5. Verify the blank preview

**Expected behavior**
Preview should not appear blank.

**Screenshots**
https://somup.com/c3noIjTncH

**Desktop:**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Comment by silvalaura** [comment]
isInverse of the DataGrid is white, and that's why it appears blank. In a recent update, we've added the background color addon to Storybook which shows here that the data is still present, but it's white:

![image](https://user-images.githubusercontent.com/91160746/162515641-7078a703-c917-4f19-9741-57f020d4a39c.png)

https://storybook-preview-636--upbeat-sinoussi-f675aa.netlify.app/?path=/story/datagrid--default&args=isInverse:true&globals=backgrounds.value:!hex(333333)

The component is functioning as designed, so closing as won't fix.
