### ISSUE TITLE
Tabs: a11y bug / aria-label

### ISSUE THREAD

**Issue by orion-cengage** [cengage/react-magma#608]
The following bug was found in 2.5.8 and reported by Shawn Haley.

![image](https://user-images.githubusercontent.com/24397282/159716785-90503ba8-bc14-432d-b641-c361b56f4f84.png)

**Comment by Uditsingh67** [comment]
The issue is fixed for Tabs components.
<html>
<body>


OS | Version | Result
-- | -- | --
Win 10 (Chrome) | 102.0.5005.63 | PASS (http://somup.com/c3jbivu9Y8)
Win 10 (Firefox) | 101.0 | PASS (http://somup.com/c3jbiau9r3)
Win 10 (Edge) | 103.0.1264.37 | PASS (http://somup.com/c3jbi4u9rI)
MAC (safari) | 15.3 | PASS (http://somup.com/c3jbipu9rH)
Ipad (safari) | v15.1 | PASS (http://somup.com/c3jbiGu93f)


</body>
</html>

**Comment by Uditsingh67** [comment]
Issue does not exist.
See Screen-cast : http://somup.com/c3jwfIU2oC
