### ISSUE TITLE
ButtonGroup: `The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type"`

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#905]
**Describe the bug**
ButtonGroup gives this error:
<img width="949" alt="Screenshot 2022-08-29 at 23 37 29" src="https://user-images.githubusercontent.com/91160746/187465511-4aef7dba-7296-45f0-b892-b22b179e8ace.png">

**To Reproduce**
1. Go to the ButtonGroup styleguide or docs site
2. Open the console
3. This also appears in unit tests

**Expected behavior**
No error or warning exists.

**Additional context**
We'll need to rethink how we style ButtonGroup as ":first-of-type" is not equivalent to ":first-child". This ticket is to figure out if there's a workaround to this while keeping the same styles.

**Comment by silvalaura** [comment]
This is super annoying and every one of our adopters gets this warning in their console. The downside is that it's not a straightforward fix 🙃

**Comment by silvalaura** [comment]
This is related to the version of Storybook we are on. Could potentially be addressed when we look at [#1064](https://github.com/cengage/react-magma/issues/1064).

**Comment by nikitaorliak-cengage** [comment]
This error appears not only in the `ButtonGroup` component. Every component with `argTypes` prop has this problem. This issue happens because our version of storybook is quite old and we need to upgrade it from 6.5.10 to 7+. They actually fixed this problem in later versions: https://github.com/storybookjs/storybook/issues/18103 -> https://github.com/storybookjs/storybook/issues/20730.
